### ISSUE TITLE
Rule lines with spaces only

### ISSUE THREAD

**Issue by GaryShelden** [def-gthill/lexurgy#15] opened 2020-11-26 18:11 UTC
Sometimes it is convenient to use "special" characters, such as -, +, ?, in the Romanized form of a language.

Lexurgy gives an error when I try to declare these in the deromanizer.

ALSO:
Many text editors leave lines with one or more spaces, followed by no text. Lexurgy does not like these either.

**Comment by def-gthill** [comment] 2020-11-26 18:32
Good point, I'll need to add an escaping mechanism to handle special characters in romanizations.

The whitespace is a separate issue, so I've opened #16 for it.

**Comment by def-gthill** [comment] 2020-11-26 19:00
Can you give me examples of sound changes you've tried with whitespace-only lines that didn't work? I've tried extra whitespace in various combinations and only some of them produce errors, so I want to make sure I'm covering your case.

**Comment by def-gthill** [comment] 2020-11-27 01:52
I've implemented escaping of special characters in commit 7cc375f405542adebd5a1515467a9916219f5135, and I'll include it in the next release.

I added some better handling of whitespace, but I'll wait for an example of what didn't work for you before I close this issue.

**Comment by GaryShelden** [comment] 2020-11-27 05:17
> 
> 
> Can you give me examples of sound changes you've tried with whitespace-only lines that didn't work? I've tried extra whitespace in various combinations and only some of them produce errors, so I want to make sure I'm covering your case.

OK, $ $ (one space), $  $ (two spaces)
In fact any white-space at the end of a line in the rules.
Appears to be fixed in web-page (unless I was crazy to bring it up)

**Comment by GaryShelden** [comment] 2020-11-27 05:18
Thanks for being so responsive! I love lexurgy!

**Comment by def-gthill** [comment] 2020-11-27 05:33
I haven't updated the website since yesterday. The whitespace fixes aren't live yet; I'm bundling them in with the other changes you requested.

Is it possible you had tab characters in your changes when you had the problem? The main thing I fixed whitespace-wise was that tab characters weren't actually counted as whitespace, so they caused all manner of chaos.

Glad to hear you aren't experiencing the error now. Let me know if it happens again, and be sure to copy and paste several lines around the offending whitespace into your comment so I can reproduce the problem.

**Comment by def-gthill** [comment] 2020-11-27 05:36
Thanks for your kind words! I really appreciate the bug reports, they help make Lexurgy the best it can be.

**Comment by def-gthill** [comment] 2020-11-30 21:58
Now that I've released version 0.10.0, which (among other things) fixes the whitespace problems I've been able to find, I'm closing this issue. If you encounter any more whitespace problems in the new version, please open another issue.

**Closed by def-gthill** 2020-11-30 21:58 UTC
Labels: bug
