### ISSUE TITLE
doubling stress diacritics when using nasalization diacritics in rules

### ISSUE THREAD

**Issue by AdamantConlanger** [def-gthill/lexurgy#22] opened 2021-02-14 02:04 UTC
I know how to fix this: declaring the combination as a Symbol. Regardless, this should work without having to do that.
Using
`Symbol ɐ [vowellike syllabic open central lax]`
`Diacritic ˈ (floating) [stressed]`
And
`Romanizer-phonetic-twelve:`
` unchanged`
`vowel-ten:`
` n̩ => ɐ̃`
` [nasal syllabic] => n̩`
` ɐ => ɐ̃`
`Romanizer-phonetic-thirteen:`
` unchanged`
I get
`ɐˈnnɛ           => ɐˈ̃ˈnnɛ            => ɐˈ̃ˈnnɛ`
`mɐˈlɐʦɛˈrɪ      => mɐˈ̃ˈlɐ̃ʦɛˈrɪ      => mɐˈ̃ˈlɐ̃sɛˈrɪ`
being respectively the two shown Romanizers and the final result. I removed the `Then: ` from the subrules to fix double nasalization diacritics already, but it's still giving double stress marks. This is either a bug or a big mistake on my end.

**Comment by def-gthill** [comment] 2021-02-14 03:23
Sorry, what do you mean by double stress marks? What rule are you using to assign stress?

**Comment by AdamantConlanger** [comment] 2021-02-14 04:08
The rule for stress it at the top. since syllable-initial stress reading isn't possible in lexurgy, I use a simple diacritic for it. In the word `ɐˈnnɛ`, the first syllable is stressed. In `mɐˈlɐʦɛˈrɪ`, the first and third. The full declaring of Symbols is a mess, but for this, only the ɐ is important:
`Symbol ɐ [vowellike syllabic open central lax]`
I have not declared ɐ̃ as a Symbol.

The words `ɐˈnnɛ` and `mɐˈlɐʦɛˈrɪ` enter this piece of code:
`vowel-ten:`
`n̩ => ɐ̃`
`[nasal syllabic] => n̩`
`ɐ => ɐ̃`
As a result, I get
`ɐˈ̃ˈnnɛ` and `mɐˈ̃ˈlɐ̃ʦɛˈrɪ`

Notice that these results contain `ɐˈ̃ˈ`, while they should be (according to the logic the code should follow) `ɐˈ̃`
This means that lexurgy is - for some reason - duplicating the `ˈ`; the diacritic I'm using for stress.

What should, _ideally_, be happening, is that lexurgy takes the `ɐ` in `ɐˈnnɛ`, disregards the stress mark, and turns it into ɐ̃, which would give a result of `ɐ̃nnɛ`. This can be done by declaring `Symbol ɐ̃ [vowellike syllabic open central lax nasalized]` at the start, which fixes all the problems.

But imagine this is a Romanizer. Then we wouldn't want to have to declare that Symbol. Maybe we're already using it elsewhere or something. In that case, lexurgy is _supposed_ to
1 see the `ɐˈ` in `ɐˈnnɛ`
2 follow the `ɐ => ɐ̃` rule, thus turning `ɐˈ` into `ɐˈ̃`
3 give the end result of `ɐˈ̃nnɛ`

in practice, it - for some reason - gives `ɐˈ̃ˈnnɛ` instead. _this_ is the problem.

**Comment by AdamantConlanger** [comment] 2021-02-14 04:15
Here is the full context file:
https://pastebin.com/23anW5rJ

**Comment by def-gthill** [comment] 2021-02-14 07:09
I understand what you're saying now. My PC font renders the second stress diacritic overlapping the nasal diacritic, so I couldn't see it.

So why is this happening? It's because Lexurgy doesn't know what you want to do with characters unless you tell it. If you don't declare ɐ̃ as a symbol or  ̃  as a diacritic, all Lexurgy sees is two unrelated characters, ɐ followed by  ̃ . So when you have the rule ɐ => ɐ̃, Lexurgy treats it exactly as if you had ɐ => ɐə (i.e. a vowel breaking rule). When you split up a sound like this, both result sounds inherit any floating diacritics from the source sound. So when ɐ => ɐə is applied to ɐˈ, both vowels get the stress diacritic; in the same way, when you apply ɐ => ɐ̃, both the ɐ and the  ̃  get the stress diacritic.

As you've already discovered, the way to avoid this is to convince Lexurgy that  ̃  isn't an independent sound, by declaring either ɐ̃ as a symbol or  ̃  as a diacritic.

This is certainly unexpected behaviour. It might make sense to have Lexurgy automatically consider all "combining diacritic" characters to be diacritics. The thing is, I haven't found a reliable way to detect whether something is a combining diacritic. I try to detect combining diacritics to better line up the arrows in the output, and this doesn't always work. So it would be pretty confusing if Lexurgy sometimes treated diacritics as diacritics, and other times as separate symbols. I'd rather have the operation of the program be consistent than intuitive.

As for your point about the romanizer, somewhere deep in my wish list is enhancements like separate declarations that only apply to specific romanizers, but the situations where this would help seem to me to be pretty easy to work around and so low priority. (If you come across a situation where the only workaround is _really, really_ awkward, please let me know!)

So I'm afraid that, at least for now, this is a quirk of Lexurgy that we just have to put up with.

**Comment by AdamantConlanger** [comment] 2021-02-14 17:31
Oh, that makes sense. The thing that made me disregard that as a possibility was that, in all cases I've encountered, the number of elements on the left and right needs to be equal. I guess that isn't the case when you aren't modifying Features and there are more elements on the right than on the left, so this would work. Thanks for explaining it to me. No, it isn't really a problem at all, it's just that it didn't cross my mind that ɐ̃ could be interpreted as two vowels.

**Comment by def-gthill** [comment] 2024-09-30 03:49
Closing this as it's been sitting open for a long time and I'm unlikely to ever implement changes in response to it.

**Closed by def-gthill** 2024-09-30 03:49 UTC
Labels: wontfix, surprise
